services:
  - type: web
    name: zentro-portfolio
    env: python
    pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn zentro_config.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: django-insecure-zentro-production-key-change-me-12345
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: zentro-portfolio.onrender.com
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: RAILWAY_PUBLIC_DOMAIN
        value: zentro-portfolio.onrender.com
