# Generated by Django 4.2 on 2026-03-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('Web Developer', 'Web Developer'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Manager', 'Project Manager'), ('Consultant', 'Consultant'), ('AIML Developer', 'AIML Developer'), ('Java Developer', 'Java Developer'), ('Other', 'Other')], max_length=50),
        ),
    ]
