# Generated by Django 4.2 on 2026-03-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('Web Developer', 'Web Developer'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Manager', 'Project Manager'), ('Logo Designer', 'Logo Designer'), ('AIML Developer', 'AIML Developer'), ('Python Developer', 'Python Developer'), ('Other', 'Other')], max_length=50),
        ),
    ]
