# Generated by Django 4.2 on 2026-04-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_project_image_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('Web Developer', 'Web Developer'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Manager', 'Project Manager'), ('Logo Designer', 'Logo Designer'), ('AIML Developer', 'AIML Developer'), ('Python Developer', 'Python Developer'), ('Cloud Engineer', 'Cloud Engineer'), ('UI/UX Designer', 'UI/UX Designer'), ('Code Developer', 'Code Developer'), ('Project Coordinator', 'Project Coordinator'), ('Other', 'Other')], max_length=50),
        ),
    ]
